/**
 * Autogenerated by Thrift
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 */
package com.cloudera.branchreduce.impl.thrift;

import java.util.List;
import java.util.ArrayList;
import java.util.Map;
import java.util.HashMap;
import java.util.EnumMap;
import java.util.Set;
import java.util.HashSet;
import java.util.EnumSet;
import java.util.Collections;
import java.util.BitSet;
import java.nio.ByteBuffer;
import java.util.Arrays;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

public class WorkRequest implements org.apache.thrift.TBase<WorkRequest, WorkRequest._Fields>, java.io.Serializable, Cloneable {
  private static final org.apache.thrift.protocol.TStruct STRUCT_DESC = new org.apache.thrift.protocol.TStruct("WorkRequest");

  private static final org.apache.thrift.protocol.TField WORKER_ID_FIELD_DESC = new org.apache.thrift.protocol.TField("workerId", org.apache.thrift.protocol.TType.I32, (short)1);
  private static final org.apache.thrift.protocol.TField GLOBAL_STATE_FIELD_DESC = new org.apache.thrift.protocol.TField("globalState", org.apache.thrift.protocol.TType.STRING, (short)2);

  public int workerId;
  public ByteBuffer globalState;

  /** The set of fields this struct contains, along with convenience methods for finding and manipulating them. */
  public enum _Fields implements org.apache.thrift.TFieldIdEnum {
    WORKER_ID((short)1, "workerId"),
    GLOBAL_STATE((short)2, "globalState");

    private static final Map<String, _Fields> byName = new HashMap<String, _Fields>();

    static {
      for (_Fields field : EnumSet.allOf(_Fields.class)) {
        byName.put(field.getFieldName(), field);
      }
    }

    /**
     * Find the _Fields constant that matches fieldId, or null if its not found.
     */
    public static _Fields findByThriftId(int fieldId) {
      switch(fieldId) {
        case 1: // WORKER_ID
          return WORKER_ID;
        case 2: // GLOBAL_STATE
          return GLOBAL_STATE;
        default:
          return null;
      }
    }

    /**
     * Find the _Fields constant that matches fieldId, throwing an exception
     * if it is not found.
     */
    public static _Fields findByThriftIdOrThrow(int fieldId) {
      _Fields fields = findByThriftId(fieldId);
      if (fields == null) throw new IllegalArgumentException("Field " + fieldId + " doesn't exist!");
      return fields;
    }

    /**
     * Find the _Fields constant that matches name, or null if its not found.
     */
    public static _Fields findByName(String name) {
      return byName.get(name);
    }

    private final short _thriftId;
    private final String _fieldName;

    _Fields(short thriftId, String fieldName) {
      _thriftId = thriftId;
      _fieldName = fieldName;
    }

    public short getThriftFieldId() {
      return _thriftId;
    }

    public String getFieldName() {
      return _fieldName;
    }
  }

  // isset id assignments
  private static final int __WORKERID_ISSET_ID = 0;
  private BitSet __isset_bit_vector = new BitSet(1);

  public static final Map<_Fields, org.apache.thrift.meta_data.FieldMetaData> metaDataMap;
  static {
    Map<_Fields, org.apache.thrift.meta_data.FieldMetaData> tmpMap = new EnumMap<_Fields, org.apache.thrift.meta_data.FieldMetaData>(_Fields.class);
    tmpMap.put(_Fields.WORKER_ID, new org.apache.thrift.meta_data.FieldMetaData("workerId", org.apache.thrift.TFieldRequirementType.DEFAULT, 
        new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.I32)));
    tmpMap.put(_Fields.GLOBAL_STATE, new org.apache.thrift.meta_data.FieldMetaData("globalState", org.apache.thrift.TFieldRequirementType.DEFAULT, 
        new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.STRING        , true)));
    metaDataMap = Collections.unmodifiableMap(tmpMap);
    org.apache.thrift.meta_data.FieldMetaData.addStructMetaDataMap(WorkRequest.class, metaDataMap);
  }

  public WorkRequest() {
  }

  public WorkRequest(
    int workerId,
    ByteBuffer globalState)
  {
    this();
    this.workerId = workerId;
    setWorkerIdIsSet(true);
    this.globalState = globalState;
  }

  /**
   * Performs a deep copy on <i>other</i>.
   */
  public WorkRequest(WorkRequest other) {
    __isset_bit_vector.clear();
    __isset_bit_vector.or(other.__isset_bit_vector);
    this.workerId = other.workerId;
    if (other.isSetGlobalState()) {
      this.globalState = org.apache.thrift.TBaseHelper.copyBinary(other.globalState);
;
    }
  }

  public WorkRequest deepCopy() {
    return new WorkRequest(this);
  }

  @Override
  public void clear() {
    setWorkerIdIsSet(false);
    this.workerId = 0;
    this.globalState = null;
  }

  public int getWorkerId() {
    return this.workerId;
  }

  public WorkRequest setWorkerId(int workerId) {
    this.workerId = workerId;
    setWorkerIdIsSet(true);
    return this;
  }

  public void unsetWorkerId() {
    __isset_bit_vector.clear(__WORKERID_ISSET_ID);
  }

  /** Returns true if field workerId is set (has been assigned a value) and false otherwise */
  public boolean isSetWorkerId() {
    return __isset_bit_vector.get(__WORKERID_ISSET_ID);
  }

  public void setWorkerIdIsSet(boolean value) {
    __isset_bit_vector.set(__WORKERID_ISSET_ID, value);
  }

  public byte[] getGlobalState() {
    setGlobalState(org.apache.thrift.TBaseHelper.rightSize(globalState));
    return globalState == null ? null : globalState.array();
  }

  public ByteBuffer bufferForGlobalState() {
    return globalState;
  }

  public WorkRequest setGlobalState(byte[] globalState) {
    setGlobalState(globalState == null ? (ByteBuffer)null : ByteBuffer.wrap(globalState));
    return this;
  }

  public WorkRequest setGlobalState(ByteBuffer globalState) {
    this.globalState = globalState;
    return this;
  }

  public void unsetGlobalState() {
    this.globalState = null;
  }

  /** Returns true if field globalState is set (has been assigned a value) and false otherwise */
  public boolean isSetGlobalState() {
    return this.globalState != null;
  }

  public void setGlobalStateIsSet(boolean value) {
    if (!value) {
      this.globalState = null;
    }
  }

  public void setFieldValue(_Fields field, Object value) {
    switch (field) {
    case WORKER_ID:
      if (value == null) {
        unsetWorkerId();
      } else {
        setWorkerId((Integer)value);
      }
      break;

    case GLOBAL_STATE:
      if (value == null) {
        unsetGlobalState();
      } else {
        setGlobalState((ByteBuffer)value);
      }
      break;

    }
  }

  public Object getFieldValue(_Fields field) {
    switch (field) {
    case WORKER_ID:
      return new Integer(getWorkerId());

    case GLOBAL_STATE:
      return getGlobalState();

    }
    throw new IllegalStateException();
  }

  /** Returns true if field corresponding to fieldID is set (has been assigned a value) and false otherwise */
  public boolean isSet(_Fields field) {
    if (field == null) {
      throw new IllegalArgumentException();
    }

    switch (field) {
    case WORKER_ID:
      return isSetWorkerId();
    case GLOBAL_STATE:
      return isSetGlobalState();
    }
    throw new IllegalStateException();
  }

  @Override
  public boolean equals(Object that) {
    if (that == null)
      return false;
    if (that instanceof WorkRequest)
      return this.equals((WorkRequest)that);
    return false;
  }

  public boolean equals(WorkRequest that) {
    if (that == null)
      return false;

    boolean this_present_workerId = true;
    boolean that_present_workerId = true;
    if (this_present_workerId || that_present_workerId) {
      if (!(this_present_workerId && that_present_workerId))
        return false;
      if (this.workerId != that.workerId)
        return false;
    }

    boolean this_present_globalState = true && this.isSetGlobalState();
    boolean that_present_globalState = true && that.isSetGlobalState();
    if (this_present_globalState || that_present_globalState) {
      if (!(this_present_globalState && that_present_globalState))
        return false;
      if (!this.globalState.equals(that.globalState))
        return false;
    }

    return true;
  }

  @Override
  public int hashCode() {
    return 0;
  }

  public int compareTo(WorkRequest other) {
    if (!getClass().equals(other.getClass())) {
      return getClass().getName().compareTo(other.getClass().getName());
    }

    int lastComparison = 0;
    WorkRequest typedOther = (WorkRequest)other;

    lastComparison = Boolean.valueOf(isSetWorkerId()).compareTo(typedOther.isSetWorkerId());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetWorkerId()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.workerId, typedOther.workerId);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    lastComparison = Boolean.valueOf(isSetGlobalState()).compareTo(typedOther.isSetGlobalState());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetGlobalState()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.globalState, typedOther.globalState);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    return 0;
  }

  public _Fields fieldForId(int fieldId) {
    return _Fields.findByThriftId(fieldId);
  }

  public void read(org.apache.thrift.protocol.TProtocol iprot) throws org.apache.thrift.TException {
    org.apache.thrift.protocol.TField field;
    iprot.readStructBegin();
    while (true)
    {
      field = iprot.readFieldBegin();
      if (field.type == org.apache.thrift.protocol.TType.STOP) { 
        break;
      }
      switch (field.id) {
        case 1: // WORKER_ID
          if (field.type == org.apache.thrift.protocol.TType.I32) {
            this.workerId = iprot.readI32();
            setWorkerIdIsSet(true);
          } else { 
            org.apache.thrift.protocol.TProtocolUtil.skip(iprot, field.type);
          }
          break;
        case 2: // GLOBAL_STATE
          if (field.type == org.apache.thrift.protocol.TType.STRING) {
            this.globalState = iprot.readBinary();
          } else { 
            org.apache.thrift.protocol.TProtocolUtil.skip(iprot, field.type);
          }
          break;
        default:
          org.apache.thrift.protocol.TProtocolUtil.skip(iprot, field.type);
      }
      iprot.readFieldEnd();
    }
    iprot.readStructEnd();

    // check for required fields of primitive type, which can't be checked in the validate method
    validate();
  }

  public void write(org.apache.thrift.protocol.TProtocol oprot) throws org.apache.thrift.TException {
    validate();

    oprot.writeStructBegin(STRUCT_DESC);
    oprot.writeFieldBegin(WORKER_ID_FIELD_DESC);
    oprot.writeI32(this.workerId);
    oprot.writeFieldEnd();
    if (this.globalState != null) {
      oprot.writeFieldBegin(GLOBAL_STATE_FIELD_DESC);
      oprot.writeBinary(this.globalState);
      oprot.writeFieldEnd();
    }
    oprot.writeFieldStop();
    oprot.writeStructEnd();
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder("WorkRequest(");
    boolean first = true;

    sb.append("workerId:");
    sb.append(this.workerId);
    first = false;
    if (!first) sb.append(", ");
    sb.append("globalState:");
    if (this.globalState == null) {
      sb.append("null");
    } else {
      org.apache.thrift.TBaseHelper.toString(this.globalState, sb);
    }
    first = false;
    sb.append(")");
    return sb.toString();
  }

  public void validate() throws org.apache.thrift.TException {
    // check for required fields
  }

  private void writeObject(java.io.ObjectOutputStream out) throws java.io.IOException {
    try {
      write(new org.apache.thrift.protocol.TCompactProtocol(new org.apache.thrift.transport.TIOStreamTransport(out)));
    } catch (org.apache.thrift.TException te) {
      throw new java.io.IOException(te);
    }
  }

  private void readObject(java.io.ObjectInputStream in) throws java.io.IOException, ClassNotFoundException {
    try {
      // it doesn't seem like you should have to do this, but java serialization is wacky, and doesn't call the default constructor.
      __isset_bit_vector = new BitSet(1);
      read(new org.apache.thrift.protocol.TCompactProtocol(new org.apache.thrift.transport.TIOStreamTransport(in)));
    } catch (org.apache.thrift.TException te) {
      throw new java.io.IOException(te);
    }
  }

}

